#!/usr/bin/env bash

tmux_pwd="$(tmux showenv $(tmux display -p 'TMUX_PWD_#D') | sed 's/^.*=//' )"

cd $tmux_pwd
echo -n "#[fg=colour234]#[fg=white, bg=colour234] $PWD "
my_dir=$(dirname $0)
$my_dir/printBranch

